# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Prj\voyager\serumsage\ui_design\sys_cfg_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sysCfgDlg(object):
    def setupUi(self, sysCfgDlg):
        sysCfgDlg.setObjectName("sysCfgDlg")
        sysCfgDlg.resize(430, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sysCfgDlg.sizePolicy().hasHeightForWidth())
        sysCfgDlg.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(sysCfgDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(sysCfgDlg)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.imgScanIntervalEdit = QtWidgets.QLineEdit(self.widget_2)
        self.imgScanIntervalEdit.setObjectName("imgScanIntervalEdit")
        self.horizontalLayout.addWidget(self.imgScanIntervalEdit)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tubeImgFolderEdit = QtWidgets.QLineEdit(self.widget_3)
        self.tubeImgFolderEdit.setObjectName("tubeImgFolderEdit")
        self.horizontalLayout_2.addWidget(self.tubeImgFolderEdit)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.detectOutputFolderEdit = QtWidgets.QLineEdit(self.widget_4)
        self.detectOutputFolderEdit.setObjectName("detectOutputFolderEdit")
        self.horizontalLayout_3.addWidget(self.detectOutputFolderEdit)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(sysCfgDlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.sysCfgDlgBtnBox = QtWidgets.QDialogButtonBox(sysCfgDlg)
        self.sysCfgDlgBtnBox.setOrientation(QtCore.Qt.Horizontal)
        self.sysCfgDlgBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.sysCfgDlgBtnBox.setObjectName("sysCfgDlgBtnBox")
        self.verticalLayout.addWidget(self.sysCfgDlgBtnBox)

        self.retranslateUi(sysCfgDlg)
        self.sysCfgDlgBtnBox.accepted.connect(sysCfgDlg.accept) # type: ignore
        self.sysCfgDlgBtnBox.rejected.connect(sysCfgDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(sysCfgDlg)

    def retranslateUi(self, sysCfgDlg):
        _translate = QtCore.QCoreApplication.translate
        sysCfgDlg.setWindowTitle(_translate("sysCfgDlg", "Dialog"))
        self.label.setText(_translate("sysCfgDlg", "图片文件扫描间隔(秒):"))
        self.label_2.setText(_translate("sysCfgDlg", "血清试管图片文件夹:"))
        self.label_3.setText(_translate("sysCfgDlg", "分析结果输出文件夹:"))
